branch-defaults:
  default:
    environment: isthe7runningcom-dev
global:
  application_name: isthe7running.com
  default_ec2_keyname: aws-eb
  default_platform: Python 2.7
  default_region: null
  profile: null
